### ISSUE TITLE
Black Face Fix

### ISSUE THREAD

**Issue by khoa-tran202** [DragonBlame/tpf-dragons-edition#12]
Hi DragonBlame,

First of all, I'd like to thank all of your efforts as well as Phoenix in making this stable and detailed modding guide. Such a wonderful world the skyrim can be!

Regarding this "Black Face Bug", I found out that the culprit is DIVERSE SKYRIM mod in MISCELLANEOUS EXTENDED section. To get rid of it, simply install **Face Discoloration Fix** mod, place it below DIVERSE SKYRIM and that's it!
https://www.nexusmods.com/skyrimspecialedition/mods/42441?tab=files

**Comment by DragonBlame** [comment]
Hello! Thank you!
The culprit technically isn't Diverse Skyrim, but me. :D 
I hope all black faces will be fixed with the next update.
