### ISSUE TITLE
Outdated ENB

### ISSUE THREAD

**Issue by Barsook81** [DragonBlame/tpf-dragons-edition#14]
Utilizing the latest build (1.6.2.1) on Wabbajack mods list the install fails as ENB can not be downloaded. Called for version 0.462 is no longer available for download being replaced by 0.463. Could you update or is there a workaround?

Thanks
Gryshko

**Comment by DragonBlame** [comment]
Can't understand, where did you get that weird version. I didn't even have any version like that. :D
The version, which is now on Wabbajack, is 1.7. Soon there will be 1.8. update. Each of them uses ENB v. 0.463. Be sure to download the latest .wabbajack again from the add-on's Google Drive.
